import React from 'react';
import clsx from 'clsx';
import type { ReceiptPaperWidth } from '../utils/receiptGenerator';

export function PrintReceipt(props: {
  /** HTML for a single copy */
  receiptHtml: string;
  copies?: number;
  paperWidth: ReceiptPaperWidth;
  className?: string;
}) {
  const copies = typeof props.copies === 'number' && props.copies > 0 ? Math.floor(props.copies) : 2;

  return (
    <div className={clsx('print-root', props.className)} data-paper-width={props.paperWidth}>
      {Array.from({ length: copies }).map((_, idx) => (
        <div
          key={idx}
          className={clsx('receipt-copy', idx === copies - 1 && 'receipt-copy-last')}
          // receiptHtml is generated by our own code; we still escape user-facing text in receiptGenerator
          dangerouslySetInnerHTML={{ __html: props.receiptHtml }}
        />
      ))}
    </div>
  );
}

